server:
  port: 8099
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://localhost:8888
          predicates:
            - Path=/api/**
          # 网关过滤器
          filters:
            - AddRequestHeader=yao,swag
#            - AddRequestParameter=name,blue
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                #转向到哪里
#                fallbackUri: forward:/fallback
#        - id: yao-fallback
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848



