spring:
  application:
    name: yaoapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yaoapi
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    #host: 192.168.230.128
    host: 116.62.230.1
    port: 6379
    #password: 123456
    password: 18270122455yjh.
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 2397806471@qq.com
    password: nlmaldbuopkjeadf
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: utf-8

server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
yao:
  api:
    access-key: yaojiahua
    sercet-key: yaojiahua

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848


aliyun:
  oss:
    file:
      endPoint: "oss-cn-beijing.aliyuncs.com"
      keyid: "LTAI5t9Mzm5dLRdK2zPhPe56"
      keysecret: "iOltG2bkmaVRCZ9o33ImzsDPH9eS2t"
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: "logistics-back-pic"
