spring:
  application:
    name: yaoapi-backend
  # DataSource Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yaoapi
#    username: root
#    password: 123456
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xx
    username: x
    password: x
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    #host: 192.168.230.128
    host: x
    port: 6379
    # 数据库索引
    database: 1
    #password: 123456
    password: x
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  #邮箱配置
  mail:
    host: smtp.qq.com
    username: x
    password: x
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: utf-8


server:
  port: 7529
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




aliyun:
  oss:
    file:
      endPoint: "x
      keyid: "x
      keysecret: x
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: x
dubbo:
  application:
    name: x
  protocol:
    name: dubbo
    port: -1
  registry:
    address: x
